-- matugen.lua — AUTO-GENERATED by Matugen. Do not hand-edit; re-run `cosmic-matugen`.
-- Material You colors from the current wallpaper (dark).
vim.o.background = "dark"
vim.o.termguicolors = true
vim.g.colors_name = "matugen"

local H = vim.api.nvim_set_hl
local c = {
  bg = "#0e1514",
  bg_alt = "#161d1c",
  bg_raise = "#252b2b",
  fg = "#dde4e3",
  fg_dim = "#bec9c7",
  fg_mute = "#889392",
  border = "#3f4948",
  primary = "#80d5d2",
  on_primary = "#003736",
  secondary = "#b0ccca",
  tertiary = "#b2c8e8",
  error = "#ffb4ab",
  on_error_ct = "#ffdad6",
  err_ct = "#93000a",
  ter_ct = "#324863",
  sel = "#324b4a",
}

H(0, "Normal", { fg = c.fg, bg = c.bg })
H(0, "NormalFloat", { fg = c.fg, bg = c.bg_alt })
H(0, "Comment", { fg = c.fg_mute, italic = true })
H(0, "Constant", { fg = c.secondary })
H(0, "String", { fg = c.tertiary })
H(0, "Character", { fg = c.tertiary })
H(0, "Number", { fg = c.secondary })
H(0, "Boolean", { fg = c.secondary })
H(0, "Float", { fg = c.secondary })
H(0, "Identifier", { fg = c.fg })
H(0, "Function", { fg = c.primary })
H(0, "Statement", { fg = c.error })
H(0, "Conditional", { fg = c.error })
H(0, "Repeat", { fg = c.error })
H(0, "Label", { fg = c.primary })
H(0, "Operator", { fg = c.fg_dim })
H(0, "Keyword", { fg = c.error })
H(0, "Exception", { fg = c.error })
H(0, "PreProc", { fg = c.secondary })
H(0, "Include", { fg = c.primary })
H(0, "Define", { fg = c.secondary })
H(0, "Macro", { fg = c.secondary })
H(0, "PreCondit", { fg = c.secondary })
H(0, "Type", { fg = c.tertiary })
H(0, "StorageClass", { fg = c.secondary })
H(0, "Structure", { fg = c.secondary })
H(0, "Typedef", { fg = c.secondary })
H(0, "Special", { fg = c.primary })
H(0, "SpecialChar", { fg = c.secondary })
H(0, "Tag", { fg = c.primary })
H(0, "Delimiter", { fg = c.fg_dim })
H(0, "SpecialComment", { fg = c.fg_mute })
H(0, "Debug", { fg = c.error })
H(0, "Underlined", { fg = c.primary, underline = true })
H(0, "Error", { fg = c.on_error_ct, bg = c.err_ct })
H(0, "Todo", { fg = c.bg, bg = c.secondary, bold = true })

H(0, "Search", { fg = c.bg, bg = c.secondary })
H(0, "IncSearch", { fg = c.bg, bg = c.primary })
H(0, "CurSearch", { fg = c.bg, bg = c.primary })
H(0, "Visual", { bg = c.sel })
H(0, "CursorLine", { bg = c.bg_alt })
H(0, "CursorLineNr", { fg = c.primary, bold = true })
H(0, "LineNr", { fg = c.border })
H(0, "SignColumn", { fg = c.border, bg = c.bg })
H(0, "StatusLine", { fg = c.fg, bg = c.bg_alt })
H(0, "StatusLineNC", { fg = c.fg_mute, bg = c.bg_alt })
H(0, "WinSeparator", { fg = c.border })
H(0, "Pmenu", { fg = c.fg, bg = c.bg_alt })
H(0, "PmenuSel", { fg = c.on_primary, bg = c.primary })
H(0, "PmenuSbar", { bg = c.bg_raise })
H(0, "PmenuThumb", { bg = c.border })
H(0, "TabLine", { fg = c.fg_mute, bg = c.bg_alt })
H(0, "TabLineSel", { fg = c.primary, bg = c.bg_raise, bold = true })
H(0, "TabLineFill", { bg = c.bg_alt })
H(0, "FloatBorder", { fg = c.border, bg = c.bg_alt })
H(0, "MatchParen", { fg = c.bg, bg = c.primary, bold = true })
H(0, "Folded", { fg = c.fg_dim, bg = c.bg_alt })
H(0, "NonText", { fg = c.border })
H(0, "Whitespace", { fg = c.border })

H(0, "DiffAdd", { fg = c.tertiary })
H(0, "DiffDelete", { fg = c.error })
H(0, "DiffChange", { fg = c.secondary })
H(0, "DiffText", { fg = c.bg, bg = c.secondary })

H(0, "DiagnosticError", { fg = c.error })
H(0, "DiagnosticWarn", { fg = c.secondary })
H(0, "DiagnosticInfo", { fg = c.primary })
H(0, "DiagnosticHint", { fg = c.tertiary })
H(0, "DiagnosticUnderlineError", { undercurl = true, sp = c.error })
H(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = c.secondary })
H(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = c.primary })
H(0, "DiagnosticUnderlineHint", { undercurl = true, sp = c.tertiary })

H(0, "GitSignsAdd", { fg = c.tertiary })
H(0, "GitSignsChange", { fg = c.secondary })
H(0, "GitSignsDelete", { fg = c.error })

H(0, "SpellBad", { undercurl = true, sp = c.error })
H(0, "SpellCap", { undercurl = true, sp = c.secondary })
H(0, "SpellRare", { undercurl = true, sp = c.tertiary })
H(0, "SpellLocal", { undercurl = true, sp = c.primary })
