;;; matugen-theme.el --- Emacs theme generated from the wallpaper by Matugen -*- lexical-binding: t; no-byte-compile: t; -*-

;; AUTO-GENERATED by Matugen. Do not hand-edit; re-run `cosmic-matugen` instead.
;; Same faces as `cosmic-theme.el`; only the palette below follows the wallpaper.

(deftheme matugen
  "Emacs theme generated from the wallpaper by Matugen.")

;; ---------------------------------------------------------------------------
;; Palette
;; ---------------------------------------------------------------------------
(let ((bg        "{{colors.surface.dark.hex}}")  ; gray_1   app background
      (bg-alt    "{{colors.surface_container_lowest.dark.hex}}")  ; neutral_2  sunken panels
      (bg-raise  "{{colors.surface_container_high.dark.hex}}")  ; neutral_3  hover / pressed surfaces
      (bg-line   "{{colors.surface_container_low.dark.hex}}")  ; gray_2   highlighted lines
      (bg-mute   "{{colors.outline_variant.dark.hex}}")  ; neutral_4  dividers, line numbers
      (bg-selection "{{colors.secondary_container.dark.hex}}") ; cyan tint over bg
      (fg        "{{colors.on_surface.dark.hex}}")  ; neutral_9 main text
      (fg-1      "{{colors.on_surface_variant.dark.hex}}")  ; neutral_8 secondary text
      (fg-2      "{{colors.outline.dark.hex}}")  ; neutral_7 muted text
      (fg-3      "{{colors.outline.dark.hex}}")  ; neutral_6 comments
      (fg-4      "{{colors.surface_bright.dark.hex}}")  ; neutral_5 faint text
      (red       "{{colors.error.dark.hex}}")
      (red-bright "{{colors.on_error_container.dark.hex}}")
      (green     "{{colors.tertiary.dark.hex}}")
      (green-bright "{{colors.on_tertiary_container.dark.hex}}")
      (yellow    "{{colors.tertiary.dark.hex}}")
      (yellow-bright "{{colors.on_tertiary_container.dark.hex}}")
      (blue      "{{colors.primary.dark.hex}}")
      (blue-deep "{{colors.primary_container.dark.hex}}")
      (purple    "{{colors.tertiary.dark.hex}}")
      (purple-deep "{{colors.tertiary_container.dark.hex}}")
      (pink      "{{colors.error.dark.hex}}")
      (pink-hot  "{{colors.error.dark.hex}}")
      (orange    "{{colors.primary.dark.hex}}")
      (orange-soft "{{colors.on_primary_container.dark.hex}}")
      (warm-grey "{{colors.on_surface_variant.dark.hex}}")
      (warm-grey-dim "{{colors.outline.dark.hex}}")
      (indigo    "{{colors.secondary.dark.hex}}")
      (indigo-deep "{{colors.secondary_container.dark.hex}}"))

  (custom-theme-set-variables
   'matugen
   '(fast-but-imprecise-scrolling t)
   '(fringe-mode 4))

  (custom-theme-set-faces
   'matugen

   ;; --- base editor -------------------------------------------------------
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,orange))))
   `(region ((t (:background ,bg-selection))))
   `(secondary-selection ((t (:background ,bg-raise))))
   `(fringe ((t (:background ,bg))))
   `(vertical-border ((t (:foreground ,bg-raise))))
   `(scroll-bar ((t (:background ,bg-raise))))
   `(internal-border ((t (:background ,bg))))
   `(shadow ((t (:foreground ,fg-3))))
   `(match ((t (:foreground ,orange))))
   `(highlight ((t (:background ,bg-raise :foreground ,fg))))
   `(hl-line ((t (:background ,bg-line))))
   `(tooltip ((t (:background ,bg-raise :foreground ,fg))))
   `(escape-glyph ((t (:foreground ,orange-soft))))
   `(link ((t (:foreground ,blue :underline t))))
   `(link-visited ((t (:foreground ,purple :underline t))))
   `(trailing-whitespace ((t (:background ,bg-mute))))
   `(whitespace-space ((t (:foreground ,bg-mute))))
   `(whitespace-newline ((t (:foreground ,bg-raise))))
   `(whitespace-tab ((t (:foreground ,bg-mute))))
   `(whitespace-hspace ((t (:foreground ,bg-mute))))
   `(whitespace-indentation ((t (:foreground ,bg-mute))))

   ;; --- line numbers ------------------------------------------------------
   `(line-number ((t (:foreground ,bg-mute :background ,bg))))
   `(line-number-current-line ((t (:foreground ,orange :background ,bg-line :weight bold))))

   ;; --- mode line ----------------------------------------------------------
   `(mode-line ((t (:foreground ,fg :background ,bg-line :box (:line-width (1 . -1) :color ,bg-raise)))))
   `(mode-line-active ((t (:foreground ,fg :background ,bg-line :box (:line-width (1 . -1) :color ,bg-raise)))))
   `(mode-line-inactive ((t (:background ,bg-alt :foreground ,fg-2))))
   `(mode-line-highlight ((t (:box (:line-width 1 :color ,orange) :background ,bg-raise))))
   `(mode-line-emphasis ((t (:weight bold :foreground ,fg))))
   `(header-line ((t (:foreground ,fg :background ,bg-line))))

   ;; --- tab bar & tab line (COSMIC-style tabs) ------------------------------
   `(tab-bar ((t (:background ,bg-alt :foreground ,fg))))
   `(tab-bar-tab ((t (:background ,bg-raise :foreground ,orange :weight bold
                                  :box (:line-width (2 . -1) :color ,orange)))))
   `(tab-bar-tab-inactive ((t (:background ,bg-alt :foreground ,fg-2))))
   `(tab-bar-tab-ungrouped ((t (:background ,bg-alt :foreground ,fg-2 :box (:line-width (1 . -1) :color ,bg-raise)))))
   `(tab-bar-tab-group-current ((t (:background ,bg-alt :foreground ,orange :weight bold))))
   `(tab-bar-tab-group-inactive ((t (:background ,bg-alt :foreground ,fg-3))))
   `(tab-bar-tab-modified ((t (:background ,bg-raise :foreground ,yellow-bright))))
   `(tab-bar-button ((t (:foreground ,fg-2 :background ,bg-alt))))
   `(tab-bar-button-highlight ((t (:foreground ,orange :background ,bg-raise))))
   `(tab-bar-close-button ((t (:foreground ,fg-3))))
   `(tab-line ((t (:background ,bg-alt :foreground ,fg :height 1.0))))
   `(tab-line-tab ((t (:background ,bg-raise :foreground ,orange :weight bold
                                   :box (:line-width (2 . -1) :color ,orange)))))
   `(tab-line-tab-inactive ((t (:background ,bg-alt :foreground ,fg-2))))
   `(tab-line-tab-current ((t (:background ,bg-raise :foreground ,orange :weight bold))))
   `(tab-line-tab-modified ((t (:background ,bg-raise :foreground ,yellow-bright))))
   `(tab-line-tab-new ((t (:foreground ,orange :weight bold))))
   `(tab-line-close-button ((t (:foreground ,fg-3))))
   `(tab-line-mouse-highlight ((t (:background ,bg-raise))))

   ;; --- minibuffer / prompt ------------------------------------------------
   `(minibuffer-prompt ((t (:foreground ,orange :weight bold))))
   `(completions-common-part ((t (:foreground ,orange))))
   `(completions-first-difference ((t (:foreground ,blue-deep :weight bold))))

   ;; --- search -------------------------------------------------------------
   `(isearch ((t (:background ,orange :foreground ,bg))))
   `(isearch-fail ((t (:background ,pink-hot :foreground ,bg))))
   `(lazy-highlight ((t (:background ,"{{colors.secondary_container.dark.hex}}" :foreground ,yellow))))
   `(query-replace ((t (:inherit isearch))))

   ;; --- paren matching -----------------------------------------------------
   `(show-paren-match ((t (:background ,blue-deep :foreground ,bg :weight bold))))
   `(show-paren-mismatch ((t (:background ,pink-hot :foreground ,bg :weight bold))))

   ;; --- font lock ----------------------------------------------------------
   `(font-lock-builtin-face ((t (:foreground ,blue))))
   `(font-lock-comment-face ((t (:foreground ,fg-3 :italic t))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,fg-4 :italic t))))
   `(font-lock-constant-face ((t (:foreground ,orange))))
   `(font-lock-number-face ((t (:foreground ,orange))))
   `(font-lock-doc-face ((t (:foreground ,warm-grey-dim :italic t))))
   `(font-lock-function-name-face ((t (:foreground ,indigo))))
   `(font-lock-keyword-face ((t (:foreground ,pink))))
   `(font-lock-negation-char-face ((t (:foreground ,orange))))
   `(font-lock-operator-face ((t (:foreground ,warm-grey))))
   `(font-lock-preprocessor-face ((t (:foreground ,orange-soft))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,pink-hot))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,purple))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-type-face ((t (:foreground ,green-bright))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(font-lock-warning-face ((t (:foreground ,yellow :weight bold))))

   ;; --- tree-sitter font-lock faces (Rust, TS, Go, Python, ...) ------------
   `(font-lock-bracket-face ((t (:foreground ,warm-grey))))
   `(font-lock-delimiter-face ((t (:foreground ,fg-2))))
   `(font-lock-escape-face ((t (:foreground ,orange-soft))))
   `(font-lock-function-call-face ((t (:foreground ,indigo))))
   `(font-lock-property-name-face ((t (:foreground ,blue-deep))))
   `(font-lock-property-use-face ((t (:foreground ,blue))))
   `(font-lock-variable-use-face ((t (:foreground ,fg-1))))

   ;; --- syntax errors / whitespace errors -----------------------------------
   `(error ((t (:foreground ,red-bright :weight bold))))
   `(warning ((t (:foreground ,yellow :weight bold))))
   `(success ((t (:foreground ,green-bright))))

   ;; --- compile -------------------------------------------------------------
   `(compilation-error ((t (:foreground ,red-bright :weight bold))))
   `(compilation-warning ((t (:foreground ,yellow))))
   `(compilation-info ((t (:foreground ,blue))))
   `(compilation-mode-line-exit ((t (:foreground ,green-bright))))
   `(compilation-mode-line-fail ((t (:foreground ,red-bright))))
   `(compilation-line-number ((t (:foreground ,fg-2))))
   `(compilation-column-number ((t (:foreground ,fg-2))))
   `(compilation-message-face ((t (:foreground ,fg-2))))
   `(compilation-mode-line-run ((t (:foreground ,blue))))

   ;; --- flymake (LSP diagnostics) -------------------------------------------
   `(flymake-error ((t (:underline (:style wave :color ,red-bright)))))
   `(flymake-warning ((t (:underline (:style wave :color ,yellow)))))
   `(flymake-note ((t (:underline (:style wave :color ,blue)))))
   `(flymake-end-of-line-diag ((t (:background ,bg-raise :foreground ,fg))))

   ;; --- eldoc ---------------------------------------------------------------
   `(eldoc-highlight-function-argument ((t (:foreground ,green-bright :weight bold :underline t))))

   ;; --- dired ---------------------------------------------------------------
   `(dired-directory ((t (:foreground ,blue :weight bold))))
   `(dired-header ((t (:foreground ,orange :weight bold :underline t))))
   `(dired-flagged ((t (:foreground ,pink-hot))))
   `(dired-mark ((t (:foreground ,yellow))))
   `(dired-marked ((t (:foreground ,purple))))
   `(dired-symlink ((t (:foreground ,purple))))
   `(dired-perm-write ((t (:foreground ,yellow))))

   ;; --- org -----------------------------------------------------------------
   `(org-level-1 ((t (:foreground ,orange :weight bold))))
   `(org-level-2 ((t (:foreground ,green-bright :weight bold))))
   `(org-level-3 ((t (:foreground ,blue :weight bold))))
   `(org-level-4 ((t (:foreground ,purple :weight bold))))
   `(org-level-5 ((t (:foreground ,pink :weight bold))))
   `(org-level-6 ((t (:foreground ,yellow :weight bold))))
   `(org-level-7 ((t (:foreground ,orange-soft :weight bold))))
   `(org-level-8 ((t (:foreground ,green :weight bold))))
   `(org-document-title ((t (:foreground ,orange :weight bold :height 1.3))))
   `(org-document-info ((t (:foreground ,fg-2))))
   `(org-document-info-keyword ((t (:foreground ,fg-4))))
   `(org-meta-line ((t (:foreground ,fg-4))))
   `(org-hide ((t (:foreground ,bg-alt))))
   `(org-todo ((t (:foreground ,orange :weight bold))))
   `(org-done ((t (:foreground ,green-bright :weight bold))))
   `(org-warning ((t (:foreground ,yellow :weight bold))))
   `(org-date ((t (:foreground ,blue-deep :underline t))))
   `(org-tag ((t (:foreground ,fg-2 :background ,bg-raise))))
   `(org-code ((t (:foreground ,orange-soft :background ,bg-alt))))
   `(org-verbatim ((t (:foreground ,orange :background ,bg-alt))))
   `(org-table ((t (:foreground ,blue))))
   `(org-link ((t (:foreground ,blue :underline t))))
   `(org-footnote ((t (:foreground ,purple :underline t))))
   `(org-quote ((t (:foreground ,fg-2 :italic t))))
   `(org-checkbox ((t (:foreground ,green))))
   `(org-block ((t (:background ,bg-alt))))
   `(org-block-begin-line ((t (:foreground ,fg-4 :background ,bg-alt :italic t))))
   `(org-block-end-line ((t (:foreground ,fg-4 :background ,bg-alt :italic t))))
   `(org-scheduled ((t (:foreground ,yellow))))
   `(org-scheduled-today ((t (:foreground ,yellow))))
   `(org-agenda-date-today ((t (:foreground ,orange :weight bold :height 1.15))))
   `(org-agenda-done ((t (:foreground ,fg-4))))
   `(org-column ((t (:background ,bg-alt))))

   ;; --- magit ---------------------------------------------------------------
   `(magit-section-heading ((t (:foreground ,orange :weight bold))))
   `(magit-section-highlight ((t (:background ,bg-raise))))
   `(magit-section-heading-selection ((t (:foreground ,yellow :weight bold))))
   `(magit-branch ((t (:foreground ,purple :weight bold))))
   `(magit-branch-remote ((t (:foreground ,pink :weight bold))))
   `(magit-tag ((t (:foreground ,yellow :weight bold))))
   `(magit-log-author ((t (:foreground ,yellow))))
   `(magit-log-date ((t (:foreground ,fg-2))))
   `(magit-log-graph ((t (:foreground ,fg-2))))
   `(magit-diff-added ((t (:foreground ,green-bright))))
   `(magit-diff-added-highlight ((t (:foreground ,green :background ,"{{colors.tertiary_container.dark.hex}}"))))
   `(magit-diff-removed ((t (:foreground ,red-bright))))
   `(magit-diff-removed-highlight ((t (:foreground ,red :background ,"{{colors.error_container.dark.hex}}"))))
   `(magit-diff-context ((t (:foreground ,fg-2))))
   `(magit-diff-context-highlight ((t (:foreground ,fg-2 :background ,bg-raise))))
   `(magit-diff-file-heading ((t (:foreground ,fg :background ,bg-alt :weight bold))))
   `(magit-diff-file-heading-highlight ((t (:foreground ,fg :background ,bg-raise :weight bold))))
   `(magit-diff-hunk-heading ((t (:foreground ,blue :background ,bg-raise))))
   `(magit-diff-hunk-heading-highlight ((t (:foreground ,blue :background ,bg-mute))))
   `(magit-diff-lines-heading ((t (:foreground ,bg :background ,indigo))))
   `(magit-header-line ((t (:background ,bg-line :foreground ,fg :weight bold))))
   `(magit-process-ok ((t (:foreground ,green-bright))))
   `(magit-process-ng ((t (:foreground ,red-bright))))
   `(magit-dimmed ((t (:foreground ,fg-4))))
   `(magit-hash ((t (:foreground ,blue-deep))))
   `(magit-reflog-other ((t (:foreground ,yellow))))
   `(magit-keyword-squash ((t (:foreground ,purple))))

   ;; --- diff -----------------------------------------------------------------
   `(diff-header ((t (:foreground ,indigo :background ,bg-alt))))
   `(diff-file-header ((t (:foreground ,blue :weight bold))))
   `(diff-added ((t (:foreground ,green-bright))))
   `(diff-removed ((t (:foreground ,red-bright))))
   `(diff-changed ((t (:foreground ,yellow))))
   `(diff-refine-added ((t (:background ,"{{colors.tertiary_container.dark.hex}}" :foreground ,green-bright))))
   `(diff-refine-removed ((t (:background ,"{{colors.error_container.dark.hex}}" :foreground ,red-bright))))

   ;; --- git-gutter / vc -------------------------------------------------------
   `(git-commit-summary ((t (:foreground ,fg :weight bold))))
   `(git-commit-keyword ((t (:foreground ,orange))))

   ;; --- vertico (minibuffer completion) ----------------------------------------
   `(vertico-current ((t (:background ,bg-raise :foreground ,fg))))
   `(vertico-group-title ((t (:foreground ,orange :background ,bg))))
   `(vertico-multiline ((t (:foreground ,fg-2))))

   ;; --- corfu (in-buffer completion) -------------------------------------------
   `(corfu-default ((t (:background ,bg-alt :foreground ,fg))))
   `(corfu-current ((t (:background ,bg-raise :foreground ,orange))))
   `(corfu-bar ((t (:background ,bg-mute))))
   `(corfu-border ((t (:background ,bg-raise))))
   `(corfu-indexed ((t (:foreground ,purple))))
   `(corfu-echo ((t (:background ,bg-raise :foreground ,fg))))

   ;; --- marginalia --------------------------------------------------------------
   `(marginalia-documentation ((t (:foreground ,fg-2))))
   `(marginalia-file-name ((t (:foreground ,blue))))
   `(marginalia-rich ((t (:foreground ,warm-grey-dim))))
   `(marginalia-size ((t (:foreground ,yellow))))
   `(marginalia-type ((t (:foreground ,purple))))
   `(marginalia-value ((t (:foreground ,green-bright))))
   `(marginalia-lighter ((t (:foreground ,fg-4))))
   `(marginalia-mode ((t (:foreground ,green))))
   `(marginalia-date ((t (:foreground ,yellow))))

   ;; --- which-key ----------------------------------------------------------------
   `(which-key-key ((t (:foreground ,blue))))
   `(which-key-separator ((t (:foreground ,fg-3))))
   `(which-key-command-description ((t (:foreground ,fg))))
   `(which-key-group-description ((t (:foreground ,purple))))
   `(which-key-docstring ((t (:foreground ,fg-2))))
   `(which-key-local-map-description ((t (:foreground ,orange))))

   ;; --- rainbow-delimiters -------------------------------------------------------
   `(rainbow-delimiters-depth-1-face ((t (:foreground ,pink))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,orange))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,green-bright))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,blue))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,purple))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,yellow))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,blue-deep))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,orange-soft))))
   `(rainbow-delimiters-mismatched-face ((t (:foreground ,bg :background ,pink-hot :weight bold))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,bg :background ,pink-hot :weight bold))))

   ;; --- doom-modeline --------------------------------------------------------------
   `(doom-modeline-buffer-file ((t (:foreground ,fg))))
   `(doom-modeline-buffer-modified ((t (:foreground ,orange :weight bold))))
   `(doom-modeline-buffer-path ((t (:foreground ,fg-2))))
   `(doom-modeline-project-dir ((t (:foreground ,orange :weight bold))))
   `(doom-modeline-info ((t (:foreground ,blue))))
   `(doom-modeline-warning ((t (:foreground ,yellow))))
   `(doom-modeline-error ((t (:foreground ,red-bright))))
   `(doom-modeline-debugger ((t (:foreground ,red-bright))))
   `(doom-modeline-bar ((t (:background ,orange))))
   `(doom-modeline-highlight ((t (:background ,bg-raise :foreground ,orange))))
   `(doom-modeline-unread-number ((t (:foreground ,purple))))
   `(doom-modeline-battery ((t (:foreground ,green-bright))))
   `(doom-modeline-battery-critical ((t (:foreground ,red-bright :weight bold))))
   `(doom-modeline-urgent ((t (:foreground ,pink-hot :weight bold))))

   ;; --- term / ansi ---------------------------------------------------------------
   `(term-color-black ((t (:foreground ,bg :background ,bg))))
   `(term-color-red ((t (:foreground ,red :background ,red))))
   `(term-color-green ((t (:foreground ,green :background ,green))))
   `(term-color-yellow ((t (:foreground ,yellow :background ,yellow))))
   `(term-color-blue ((t (:foreground ,blue :background ,blue))))
   `(term-color-magenta ((t (:foreground ,purple :background ,purple))))
   `(term-color-cyan ((t (:foreground ,blue-deep :background ,blue-deep))))
   `(term-color-white ((t (:foreground ,fg-1 :background ,fg-1))))
   `(term-default-bg-color ((t (:background ,bg))))
   `(term-default-fg-color ((t (:foreground ,fg))))
   `(ansi-color-black ((t (:background ,bg :foreground ,bg))))
   `(ansi-color-red ((t (:background ,red :foreground ,red))))
   `(ansi-color-green ((t (:background ,green :foreground ,green))))
   `(ansi-color-yellow ((t (:background ,yellow :foreground ,yellow))))
   `(ansi-color-blue ((t (:background ,blue :foreground ,blue))))
   `(ansi-color-magenta ((t (:background ,purple :foreground ,purple))))
   `(ansi-color-cyan ((t (:background ,blue-deep :foreground ,blue-deep))))
   `(ansi-color-white ((t (:background ,fg-1 :foreground ,fg-1))))
   `(ansi-color-bright-black ((t (:background ,fg-4 :foreground ,fg-4))))
   `(ansi-color-bright-red ((t (:background ,red-bright :foreground ,red-bright))))
   `(ansi-color-bright-green ((t (:background ,green-bright :foreground ,green-bright))))
   `(ansi-color-bright-yellow ((t (:background ,yellow-bright :foreground ,yellow-bright))))
   `(ansi-color-bright-blue ((t (:background ,indigo :foreground ,indigo))))
   `(ansi-color-bright-magenta ((t (:background ,purple-deep :foreground ,purple-deep))))
   `(ansi-color-bright-cyan ((t (:background ,blue :foreground ,blue))))
   `(ansi-color-bright-white ((t (:background ,fg :foreground ,fg))))

   ;; --- comint / eshell -----------------------------------------------------------
   `(comint-highlight-prompt ((t (:foreground ,green-bright :weight bold))))
   `(eshell-prompt ((t (:foreground ,green-bright :weight bold))))
   `(eshell-ls-directory ((t (:foreground ,blue :weight bold))))
   `(eshell-ls-symlink ((t (:foreground ,purple))))
   `(eshell-ls-executable ((t (:foreground ,green-bright))))
   `(eshell-ls-backup ((t (:foreground ,fg-4))))

   ;; --- messages / info --------------------------------------------------------------
   `(message-header-to ((t (:foreground ,blue :weight bold))))
   `(message-header-cc ((t (:foreground ,pink :weight bold))))
   `(message-header-subject ((t (:foreground ,orange :weight bold))))
   `(message-header-newsgroups ((t (:foreground ,purple))))
   `(message-header-other ((t (:foreground ,green-bright))))
   `(message-header-name ((t (:foreground ,fg-3))))
   `(message-separator ((t (:foreground ,fg-4))))
   `(message-cited-text ((t (:foreground ,fg-2 :italic t))))
   `(message-mml ((t (:foreground ,purple))))
   `(info-header-node ((t (:foreground ,green-bright))))
   `(info-xref ((t (:foreground ,blue :underline t))))
   `(info-xref-visited ((t (:foreground ,purple :underline t))))
   `(info-menu-star ((t (:foreground ,pink))))

   ;; --- misc UI ----------------------------------------------------------------------
   `(button ((t (:foreground ,blue :underline t))))
   `(widget-button ((t (:foreground ,blue :underline t))))
   `(widget-field ((t (:background ,bg-raise))))
   `(widget-single-line-field ((t (:background ,bg-raise))))
   `(bm-fringe-face ((t (:background ,blue-deep))))
   `(highlight-quoted-quote ((t (:foreground ,yellow))))
   `(highlight-quoted-symbol ((t (:foreground ,green-bright))))
   `(help-key-binding ((t (:background ,bg-raise :foreground ,yellow :weight bold))))
   `(apropos-symbol ((t (:foreground ,blue :weight bold))))
   `(log-view-message ((t (:foreground ,yellow))))))


;;;###autoload
(and load-file-name
     (boundp 'custom-theme-load-path)
     (add-to-list 'custom-theme-load-path
                  (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'matugen)

;;; matugen-theme.el ends here